.PHONY: clean

T0= 00_linked_list
T1= 01_second_linked_list
T2= 02_third_linked_list
T3= 03_fourth_linked_list
T4= 04_reverse_linked_list
T5= 05_recursive_print
T6= 06_recursion_reverse_list
T7= 07_doubly_linked_list
T8= 08_stack_using_arrays
T9= 09_stack_using_linked_list
T10= 10_stack_STL
T11= 11_stack_balancing_paranthesis
T12= 12_stack_postfix_evaluation
T13= 13_stack_infix_to_postfix
T14= 14_queues_and_operations
T15= 15_trees_BST
TARGETS= $(T1) $(T2) $(T3) $(T4) $(T5) $(T6) $(T7) $(T8) $(T9) $(T10) $(T11) $(T12) $(T13) $(T14) $(T15) 

FLAGS= -std=c++11 -Wall -Werror

all: $(TARGETS)


$(T1): $(T1).cpp
	g++ $< -o $@ $(FLAGS)

$(T2): $(T2).cpp
	g++ $< -o $@ $(FLAGS)

$(T3): $(T3).cpp
	g++ $< -o $@ $(FLAGS)

$(T4): $(T4).cpp
	g++ $< -o $@ $(FLAGS)

$(T5): $(T5).cpp
	g++ $< -o $@ $(FLAGS)

$(T6): $(T6).cpp
	g++ $< -o $@ $(FLAGS)		

$(T7): $(T7).cpp
	g++ $< -o $@ $(FLAGS)

$(T8): $(T8).cpp
	g++ $< -o $@ $(FLAGS)

$(T9): $(T9).cpp
	g++ $< -o $@ $(FLAGS)

$(T10): $(T10).cpp
	g++ $< -o $@ $(FLAGS)

$(T11): $(T11).cpp
	g++ $< -o $@ $(FLAGS)

$(T12): $(T12).cpp
	g++ $< -o $@ $(FLAGS)

$(T13): $(T13).cpp
	g++ $< -o $@ $(FLAGS)

$(T14): $(T14).cpp
	g++ $< -o $@ $(FLAGS)

$(T15): $(T15).cpp
	g++ $< -o $@ $(FLAGS)


clean:
	rm $(T1) $(T2) $(T3) $(T4) $(T5) $(T6) $(T7) $(T8) $(T9) $(T10) $(T11) $(T12) $(T13) $(T14) $(T15)
